/*
 * This java source file is generated by DAO4J v1.19
 * Generated on Mon May 18 08:42:30 CDT 2015
 * For more information, please contact b-i-d@163.com
 * Please check http://sourceforge.net/projects/dao4j/ for the latest version.
 */

package dao4j.sample;

/*
 * For Table Producto
 */
public class Producto implements java.io.Serializable, Cloneable {
    private ProductoKey _key = new ProductoKey();

    /* idProducto, PK */
    protected int idproducto;

    /* imagen */
    protected java.sql.Blob imagen;

    /* producto */
    protected String producto;

    /* descripcion */
    protected String descripcion;

    /* precio */
    protected double precio;

    /* existencia */
    protected int existencia;

    /* Return the key object. */
    public ProductoKey getKeyObject() {
        return _key;
    }

    /* idProducto, PK */
    public int getIdproducto() {
        return idproducto;
    }

    /* idProducto, PK */
    public void setIdproducto(int idproducto) {
        this.idproducto = idproducto;
        _key.setIdproducto(idproducto);
    }

    /* imagen */
    public java.sql.Blob getImagen() {
        return imagen;
    }

    /* imagen */
    public void setImagen(java.sql.Blob imagen) {
        this.imagen = imagen;
    }

    /* producto */
    public String getProducto() {
        return producto;
    }

    /* producto */
    public void setProducto(String producto) {
        this.producto = producto;
    }

    /* descripcion */
    public String getDescripcion() {
        return descripcion;
    }

    /* descripcion */
    public void setDescripcion(String descripcion) {
        this.descripcion = descripcion;
    }

    /* precio */
    public double getPrecio() {
        return precio;
    }

    /* precio */
    public void setPrecio(double precio) {
        this.precio = precio;
    }

    /* existencia */
    public int getExistencia() {
        return existencia;
    }

    /* existencia */
    public void setExistencia(int existencia) {
        this.existencia = existencia;
    }

    /* Indicates whether some other object is "equal to" this one. */
    public boolean equals(Object obj) {
        if (this == obj)
            return true;

        if (obj == null || !(obj instanceof Producto))
            return false;

        Producto bean = (Producto) obj;

        if (this.idproducto != bean.idproducto)
            return false;

        if (this.imagen == null) {
            if (bean.imagen != null)
                return false;
        }
        else if (!this.imagen.equals(bean.imagen)) 
            return false;

        if (this.producto == null) {
            if (bean.producto != null)
                return false;
        }
        else if (!this.producto.equals(bean.producto)) 
            return false;

        if (this.descripcion == null) {
            if (bean.descripcion != null)
                return false;
        }
        else if (!this.descripcion.equals(bean.descripcion)) 
            return false;

        if (this.precio != bean.precio)
            return false;

        if (this.existencia != bean.existencia)
            return false;

        return true;
    }

    /* Creates and returns a copy of this object. */
    public Object clone()
    {
        Producto bean = new Producto();
        bean.idproducto = this.idproducto;
        bean.imagen = this.imagen;   // The field (java.sql.Blob) is not cloned actually.
        bean.producto = this.producto;
        bean.descripcion = this.descripcion;
        bean.precio = this.precio;
        bean.existencia = this.existencia;
        return bean;
    }

    /* Returns a string representation of the object. */
    public String toString() {
        String sep = "\r\n";
        StringBuffer sb = new StringBuffer();
        sb.append(this.getClass().getName()).append(sep);
        sb.append("[").append("idproducto").append(" = ").append(idproducto).append("]").append(sep);
        sb.append("[").append("imagen").append(" = ").append(imagen).append("]").append(sep);
        sb.append("[").append("producto").append(" = ").append(producto).append("]").append(sep);
        sb.append("[").append("descripcion").append(" = ").append(descripcion).append("]").append(sep);
        sb.append("[").append("precio").append(" = ").append(precio).append("]").append(sep);
        sb.append("[").append("existencia").append(" = ").append(existencia).append("]").append(sep);
        return sb.toString();
    }
}