/*
 * This java source file is generated by DAO4J v1.19
 * Generated on Mon May 18 08:42:30 CDT 2015
 * For more information, please contact b-i-d@163.com
 * Please check http://sourceforge.net/projects/dao4j/ for the latest version.
 */

package dao4j.sample;

public class ProductoKey implements java.io.Serializable, Cloneable {
    /* idProducto */
    protected int idproducto;

    /* idProducto */
    public int getIdproducto() {
        return idproducto;
    }

    /* idProducto */
    public void setIdproducto(int idproducto) {
        this.idproducto = idproducto;
    }

    /* Calculate hash code */
    public int hashCode() {
        int hashCode = 0;
        hashCode += new Integer(idproducto).hashCode();
        return hashCode;
    }
    
    /* Indicates whether some other object is "equal to" this one. */
    public boolean equals(Object obj) {
        if (this == obj)
            return true;

        if (obj == null || !(obj instanceof ProductoKey))
            return false;

        ProductoKey key = (ProductoKey) obj;

        if (this.idproducto != key.idproducto)
            return false;

        return true;
    }

    /* Creates and returns a copy of this object. */
    public Object clone()
    {
        ProductoKey key = new ProductoKey();
        key.idproducto = this.idproducto;
        return key;
    }

    /* Returns a string representation of the object. */
    public String toString() {
        String sep = "\r\n";
        StringBuffer sb = new StringBuffer();
        sb.append(this.getClass().getName()).append(sep);
        sb.append("[").append("idproducto").append(" = ").append(idproducto).append("]");
        return sb.toString();
    }
}